### ISSUE TITLE
Any way to render but keep the original block contents?

### ISSUE THREAD

**Issue by Gitbreast** [stdword/logseq13-full-house-plugin#1]
Looking for a quick way to insert a wiki link using the current page name, first I consider `logseq-powerblocks-plugin` then cannibalox in forum recommend this.Then I experience this powerful plugin, it deal with the variable such as page name perfectly.

But while I use it in page property block, I realize it renders after clearing the original content of the block. That means it can't be use in a block that has any content. I think this would cause a big limit to its powerful feature.

So I think is it any way to **add** the template content but **do not clear or replace** the original content, just like `logseq-powerblocks-plugin`?

Discussion: https://discuss.logseq.com/t/any-way-to-get-variables-value-in-custom-commands/15994/1

**Comment by stdword** [comment]
Hello! Thank you for response and feedback! It is really important to me.

**Quick response**: It is a bug I'm aware of and will be fixed at the very next version.

**Comment by stdword** [comment]
@Gitbreast check v1.3.0

**Comment by Gitbreast** [comment]
@stdword It seems not work. Honestly, even worse for me🤣

OS: MacOS Lastest
Logseq version: 0.8.18
Plugin version: 1.3.0

My template:
<img width="420" alt="截屏2023-03-21 00 37 47" src="https://user-images.githubusercontent.com/96460796/226412584-d89b5e4f-0450-4600-81f3-17107e8fe8f9.png">
My command:
<img width="400" alt="截屏2023-03-21 00 34 13" src="https://user-images.githubusercontent.com/96460796/226412812-07d22b77-ebf8-4960-9e43-ae319f6952c7.png">
Normally, it still always clears the block content then render:
![屏幕录制2023-03-21 00 31 51](https://user-images.githubusercontent.com/96460796/226413973-faaba44a-ff0d-4c77-9dba-e645ad5cbf80.gif)
Sometimes, such as toggle off then toggle on the plugin, without reload(cmd+R) then use directly, it would provide 2 templates at a time and wiggle the page a bit:
![屏幕录制2023-03-21 00 35 43](https://user-images.githubusercontent.com/96460796/226415143-58ad423b-5210-4acd-a79e-32e87802f4dd.gif)

**Comment by stdword** [comment]
Wow! I need to say sorry for misunderstanding.
I've read you words:
> do not clear or replace the original content
And fix for another case: clearing block content when _inserting_ renderer command, not a _rendering_ itself.

→ reopen for now

**Comment by stdword** [comment]
Now it works as you expect:
<video src="https://user-images.githubusercontent.com/1984175/226592634-e1967483-6a27-43ec-a67b-f64d7a315a8a.mp4"/>

I'll check your exact case with inserting code inside macro later today.

**Comment by Gitbreast** [comment]
@stdword Cool! Thanks for the work! I already tested it, it works well now, also with macros.

Another question: Is it possible or a good idea to hide it in Logseq template menu? A setting to switch, or use different property name like “`template+`” or something like that, to avoid it showing in sys-template menu?

Because of the variables, these “enhanced templates" almost won’t be used in sys-template menu. With time passed, a predictable situation is, normal templates will mix up with them and hard to be pick out.

**Comment by stdword** [comment]
You prev question:
> Sometimes, such as toggle off then toggle on the plugin, without reload(cmd+R) then use directly, it would provide 2 templates at a time and wiggle the page a bit

I guess this is Logseq bug with load/reload mechanics of plugins. I face it every day during development. But my investigation give no results on how to fix / hack / avoid it for now 😢 

> Is it possible or a good idea to hide it in Logseq template menu? A setting to switch, or use different property name like “template+” or something like that, to avoid it showing in sys-template menu?

Mixing up with native templates very likely, yes. I have several ideas to solve it:
1) 📅 [future] Support **native templates syntax** to smoothly render them when need. Thus, you can render all your templates with `Full House` no matter which type they are. Native template renderer will be left behind.
2) 📅 [future] **Template selectors** feature: a way to restrict all your templates list by some rule. This rule could be context oriented: for pages with name starts with specified prefix use only selected templates. Or bind specified shortcut to all templates, related to education and another shortcut to all templates related to work. Or hidden by default templates, etc. This idea needs a research and product design work. May be you could address some thoughts here.
3) 📅 [future] **Inline templates** feature. In your «wiki EN» template example: if `Full House` template renderer could render template by specifying its body just inside the renderer macro — there is no need to give it a name at all. Thus the won't be mixed with other templates.
4) ✅ [now] You already don't need to specify a name for you template. `Full House` could **render any block** as a template — just use block context menu. The restriction here is that you can't wrap it in command or macro like «wiki EN». Because Logseq resets block uuids on every app restart with one exception: if there is an internal reference to that block — uuid will be preserved.

How do you think will these features help in scenario you've provided?

**Comment by Gitbreast** [comment]
WOW sounds great and exciting.
1. Does it mean full-house could completely replace native template entrance and use “/template” to call up, if the native templates syntax feature has implemented?
2. The filter feature sounds powerful. Prefix is for namespace? Related binding is for page or block properties(tags..)? Perhaps can consider a build-in property-value filter, so that can specify in a template’s property — it can be retrieved in which pages with which property and what value. It sounds is the most powerful, wouldn’t it a little complex though?
3. Easy to understand and use, but not so friendly for each time use?
4. wow. Heard this I thought I could refer the template uuid in its block as a hidden property, then uuid will be preserved so I could del the template name and use uuid to specify. But practice proved it failed.🤣

**Comment by stdword** [comment]
> Does it mean full-house could completely replace native template entrance and use “/template” to call up, if the native templates syntax feature has implemented?

Sure 😎

> The filter feature sounds ... the most powerful, wouldn’t it a little complex though?

Technically — absolutely not complex. The main caveats here is product design of the feature. I guess I'll come to community and users of `Full House` to get feedback, thoughts, usage cases, problems, etc.

> **inline templates**: Easy to understand and use, but not so friendly for each time use?

They will be very similar to `:commands` from `config.edn`. But with full house of rendering abilities 😎

> wow. Heard this I thought I could refer the template uuid in its block as a hidden property, then uuid will be preserved so I could del the template name and use uuid to specify. But practice proved it failed.🤣

I'll check this case later 👌

**Comment by stdword** [comment]
@stdword hi, again!

> I'll check this case later 👌

I promised to return to this point and now it fixed with the last version of `🏛 Full House Template`: just use copy command from context menu block and block uuid WILL be preserved.

Also note a new big feature — `:template-view`. With views you can create cool auto-rendering stuff like [Deail Journal Templates](https://github.com/stdword/logseq13-full-house-plugin/blob/main/docs/showcases.md#daily-journal-template) or [Folding page references](https://github.com/stdword/logseq13-full-house-plugin/blob/main/docs/showcases.md#folding-page-references)

**Comment by Gitbreast** [comment]
@stdword Take me some time to test it. It works well now. Seems like while copying a block ref, Logseq will give a hidden block property `id::` in file.
Take me some time to notice `template::` and `template-including-parent:: false` become useless now, then I deleted all the properties of parent blocks and directly copied the `((uuid))` of template block(used to be child block) to my `config.edn`. Well done.

**Comment by stdword** [comment]
> Seems like while copying a block ref, Logseq will give a hidden block property id:: in file

Yes! And exactly the same `🏛 Full House Templates` does with context menu commands `Copy as 🏛template` and `Copy as 🏛view`.

> copied the ((uuid)) of template block(used to be child block) to my config.edn

Just to clarify your case: Do you copy it to `:commands` section?

**Comment by Gitbreast** [comment]
@stdword Yes. I use it like this.
```
 ;; Add your own commands to speedup.
 ;; E.g. [["js" "Javascript"]]
 :commands
 [ 
   ["Wiki EN" "{{renderer :template, ((64287991-819d-4893-ae70-07edc3524ac3))}}"]
   ["Wiki EN Embed" "{{renderer :template, ((64287991-cf53-498d-a4cd-e4e7cfa66b72))}}”]
   ["Douban" "{{renderer :template, ((64287991-4619-4821-9360-325a2c9d347d))}}"]
   ["saying" "#saying"] 
 ]
```
My template blocks
<img width="500" alt="image" src="https://user-images.githubusercontent.com/96460796/229349047-346dece4-97e8-404c-bb32-d4b375295371.png">
