### ISSUE TITLE
Macro style (width) changed after loading plugin

### ISSUE THREAD

**Issue by bGZo** [stdword/logseq13-full-house-plugin#22]
Thanks for your awesome job, it really helps me a lot in inserting template. Today I try to use the macro function and found the style(width) of `{{iframe }}` is not consist, whose commands I used is same as #1. 

```
:macros {
 "iframe" "<iframe src='$1' style='height:320px'></iframe>"
}
```

And here is the means to reproduce:

![Logseq_462](https://github.com/stdword/logseq13-full-house-plugin/assets/57313137/17dc02cd-077d-4434-a52f-866a65aa4b19)

I found that the plugin is not including the css code, and I have no idea how to avoid rendering this block. So I try to use another alternative solution as follows:

```
<iframe src = '' style= 'height:320px'></iframe>
template:: iframe-full-house
```

It works as well. Thus the priority of issue is not much high. I'm looking forward to fix it one day. Thanks your job again.

(Windows 11; logseq@0.9.4; losgeq13-full-house-plugin@2.6.0)

**Comment by stdword** [comment]
Hello! Thank you for the kind words about my work 🙏❤️

And thank you for pointing out the issue, I guess I forgot to remove the CSS I added to the plugin while experimenting with macros. It loads dynamically, without a separate CSS file.

The CSS was added to fight [this bug](https://github.com/logseq/logseq/issues/8623). However, since the plugin doesn't use macros and I made an appropriate [PR](https://github.com/logseq/logseq/pull/9234) to Logseq itself, I removed the CSS.

Regarding the priority and workaround you found, I haven't released the plugin yet. The fix will come with the next release, along with other features, to avoid bothering users with such a low-priority fix.

BTW: There's also another way to keep the iframe wide. By adding custom CSS for _your macro name_:
```css
div.macro[data-macro-name=iframe] {
    display: block;
}
```
